# Generated by Django 6.0.6 on 2026-07-08 23:31

import django.core.validators
import django.db.models.deletion
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(choices=[('english_lang', 'English Language'), ('english_litr', 'English Literature'), ('french_lang', 'French Language'), ('french_litr', 'French Literature'), ('german_lang', 'German Language'), ('german_litr', 'German Literature'), ('spanish_lang', 'Spanish Language'), ('spanish_litr', 'Spanish Literature'), ('ukrainian_lang', 'Ukrainian Language'), ('ukrainian_litr', 'Ukrainian Literature'), ('math', 'Math'), ('physics', 'Physics'), ('geography', 'Geography'), ('chemistry', 'Chemistry'), ('biology', 'Biology'), ('history', 'History')], editable=False, max_length=64, unique=True)),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
            },
        ),
        migrations.CreateModel(
            name='TutorCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('birth_date', models.DateField()),
                ('experience_years', models.PositiveSmallIntegerField()),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_card', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tutor Card',
                'verbose_name_plural': 'Tutor Cards',
            },
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weekday', models.PositiveSmallIntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('tutor_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='profiles.tutorcard')),
            ],
            options={
                'verbose_name': 'Availability',
                'verbose_name_plural': 'Availabilities',
            },
        ),
        migrations.CreateModel(
            name='TutorSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1)])),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('JPY', 'Japanese Yen'), ('UAH', 'Ukrainian Hryvnia')], default='USD', max_length=3)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_subjects', to='profiles.subject')),
                ('tutor_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='profiles.tutorcard')),
            ],
            options={
                'verbose_name': 'Tutor Subject',
                'verbose_name_plural': 'Tutor Subjects',
                'ordering': ['subject__name'],
                'constraints': [models.UniqueConstraint(fields=('tutor_card', 'subject'), name='unique_tutor_subject')],
            },
        ),
    ]
